### ISSUE TITLE
과제 코멘트

### ISSUE THREAD

**Issue by ChanghwanK** [Gwang-hoon-hub/board1#1]
Q&A
- 예외처리를 중요한 포인트이기 때문에 각각의 역할이 무엇인지 잘 공부하는 것이 중요한 것 같고 좋은 응답체계가 가지는 이점까지 알아본다면 좋을 것 같습니다. (모니터링 잘하기 위한 노력들)
- 전반적인 설계는 Global하게 ControllerAdvice가 요청에서 발생한 예외를 캐치 하도록 설계합니다. 그 이유는 ExceptionHandler를 각 컨트롤러마다 작성하면 코드가 복잡해지고 중복 코드가 많이 발생하기 때문 입니다.
- ResponseEntity는 더 많은 정보를 상세하게 클라이언트에게 제공하기 위함 입니다. 이렇게 단일화된 포맷으로 통일하는 것이 클라이언트 입장에서도 좋고 모니터링 관점에서도 유리 합니다.
- JPA는 공부할게 많은게 사실이고 천천히하다보면 잘할 수 있을 것 입니다. 파이팅 입니다.

**과제 코멘트**
- README 작성에 상당한 노력이 보여서 아주 좋습니다. 서비스 스펙을 문서화 하는 것 또한 중요한 역량이기에 이러한 포인트를 강점으로 내세워도 좋을 것 같습니다.
- 다른 과제와 다르게 레이어드 아키텍처를 일관적으로 가져간 모습 좋은 것 같습니다.
- Entity에 기본 생성자가 그냥 안전장치 없이 열려있는 것은 조금 위험해 보입니다.
- Dto를 사용용도에 맞게 잘 정의해주신 부분 좋은 것 같습니다. 다만 이렇게 되면 Dto 양이 많아진다는 관리포인트가 생길 것 같은데 어떻게 해결할 수 있을까요 힌트는 static class 입니다.

**Comment by Gwang-hoon-hub** [comment]
DevBloo님 소중한 코멘트 남겨주셔서 너무 감사합니다!
기본생성자에서 protected로 해야함을 배울 수 있었고 필요에 따라 적용하도록 노력하겠습니다.
무엇보다 제가 너무나도 궁금했던 점이 이 많은 dto를 어떻게 관리를 할 것인가라는 점이였는데 static class를 통해서 얼마나 깔끔하게 정리를 할 수 있는지를 익힐 수 있었습니다. 배운것을 다시 적용해서 조금씩 전진하는 개발자가 되도록 노력하겠습니다 감사합니다!

**Comment by Gwang-hoon-hub** [comment]
> Q&A
> 
> * 예외처리를 중요한 포인트이기 때문에 각각의 역할이 무엇인지 잘 공부하는 것이 중요한 것 같고 좋은 응답체계가 가지는 이점까지 알아본다면 좋을 것 같습니다. (모니터링 잘하기 위한 노력들)
> * 전반적인 설계는 Global하게 ControllerAdvice가 요청에서 발생한 예외를 캐치 하도록 설계합니다. 그 이유는 ExceptionHandler를 각 컨트롤러마다 작성하면 코드가 복잡해지고 중복 코드가 많이 발생하기 때문 입니다.
> * ResponseEntity는 더 많은 정보를 상세하게 클라이언트에게 제공하기 위함 입니다. 이렇게 단일화된 포맷으로 통일하는 것이 클라이언트 입장에서도 좋고 모니터링 관점에서도 유리 합니다.
> * JPA는 공부할게 많은게 사실이고 천천히하다보면 잘할 수 있을 것 입니다. 파이팅 입니다.
> 
> **과제 코멘트**
> 
> * README 작성에 상당한 노력이 보여서 아주 좋습니다. 서비스 스펙을 문서화 하는 것 또한 중요한 역량이기에 이러한 포인트를 강점으로 내세워도 좋을 것 같습니다.
> * 다른 과제와 다르게 레이어드 아키텍처를 일관적으로 가져간 모습 좋은 것 같습니다.
> * Entity에 기본 생성자가 그냥 안전장치 없이 열려있는 것은 조금 위험해 보입니다.
> * Dto를 사용용도에 맞게 잘 정의해주신 부분 좋은 것 같습니다. 다만 이렇게 되면 Dto 양이 많아진다는 관리포인트가 생길 것 같은데 어떻게 해결할 수 있을까요 힌트는 static class 입니다.

**Comment by Gwang-hoon-hub** [comment]
> Q&A
> 
> * 예외처리를 중요한 포인트이기 때문에 각각의 역할이 무엇인지 잘 공부하는 것이 중요한 것 같고 좋은 응답체계가 가지는 이점까지 알아본다면 좋을 것 같습니다. (모니터링 잘하기 위한 노력들)
> * 전반적인 설계는 Global하게 ControllerAdvice가 요청에서 발생한 예외를 캐치 하도록 설계합니다. 그 이유는 ExceptionHandler를 각 컨트롤러마다 작성하면 코드가 복잡해지고 중복 코드가 많이 발생하기 때문 입니다.
> * ResponseEntity는 더 많은 정보를 상세하게 클라이언트에게 제공하기 위함 입니다. 이렇게 단일화된 포맷으로 통일하는 것이 클라이언트 입장에서도 좋고 모니터링 관점에서도 유리 합니다.
> * JPA는 공부할게 많은게 사실이고 천천히하다보면 잘할 수 있을 것 입니다. 파이팅 입니다.
> 
> **과제 코멘트**
> 
> * README 작성에 상당한 노력이 보여서 아주 좋습니다. 서비스 스펙을 문서화 하는 것 또한 중요한 역량이기에 이러한 포인트를 강점으로 내세워도 좋을 것 같습니다.
> * 다른 과제와 다르게 레이어드 아키텍처를 일관적으로 가져간 모습 좋은 것 같습니다.
> * Entity에 기본 생성자가 그냥 안전장치 없이 열려있는 것은 조금 위험해 보입니다.
> * Dto를 사용용도에 맞게 잘 정의해주신 부분 좋은 것 같습니다. 다만 이렇게 되면 Dto 양이 많아진다는 관리포인트가 생길 것 같은데 어떻게 해결할 수 있을까요 힌트는 static class 입니다.

----

DevBloo님 소중한 코멘트 남겨주셔서 너무 감사합니다!
기본생성자에서 protected로 해야함을 배울 수 있었고 필요에 따라 적용하도록 노력하겠습니다.
무엇보다 제가 너무나도 궁금했던 점이 이 많은 dto를 어떻게 관리를 할 것인가라는 점이였는데 static class를 통해서 얼마나 깔끔하게 정리를 할 수 있는지를 익힐 수 있었습니다. 배운것을 다시 적용해서 조금씩 전진하는 개발자가 되도록 노력하겠습니다 감사합니다!
